#!/usr/bin/env python2.7
#-*- mode: Python;-*-

"""
A lightweight compile and simulate script for VCS.
Includes some support for Verdi, too.
"""

__version__       = '0.0'
__author__        = "Brian Hunter"
__email__         = 'brian.hunter@cavium.com'

import os
import subprocess
import sys
import argparse

########################################################################################
# Globals

GLBL = None
Options = None

########################################################################################
def setup_globals():
    """
    Set up the GLBL dictionary with imported information from gogo_site and the local tb.py
    """

    global GLBL

    keys = ('VCOMP_DIR' , 'UVM_REV', 'VKITS', 'FLISTS', 'PLI_FILES', 'BUILD_TOOL',
            'BUILD_OPTIONS', 'LSF_SUBMIT_TOOL', 'LSF_BUILD_LICS', 'LSF_SIM_LICS',
            'VKITS_DIR', 'UVM_DIR', 'UVM_FLIST', 'CLEAN_DIRS', 'CLEAN_FILES',
            'SIM_GUI', )

    GLBL = {it : None for it in keys}

    def import_lib(mod_name):
        try:
            lib = __import__(mod_name)
        except ImportError:
            print "!! %s.py file not found!" % mod_name
            print "!! Ensure that your PYTHONPATH variable includes '.'"
            sys.exit(1)

        lib_dict = lib.__dict__
        for key in GLBL:
            if key in lib_dict:
                GLBL[key] = lib_dict[key]

    import_lib("gogo_site")
    import_lib("tb")

    GLBL['VKITS_DIR'] = '../vkits'
    GLBL['UVM_DIR']   = os.path.join(GLBL['VKITS_DIR'], 'uvm/%s' % GLBL['UVM_REV'])
    GLBL['UVM_FLIST'] = os.path.join(GLBL['UVM_DIR'], 'uvm.flist')

    for key in GLBL:
        if GLBL[key] is None:
            print "!! %s is not defined in gogo_site.py or tb.py." % key
            sys.exit(1)

########################################################################################
def parse_args():
    """
    Parse Command-Line
    """

    global Options

    p = argparse.ArgumentParser(
        prog='gogo',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        usage="%(prog)s [verbs] [options]",
        version=("%(prog)s v"+__version__),
        description="""
Launch SV compile and/or simulation with simulator.
        """)

    verb_choices = ['bld', 'sim', 'cln', 'b', 's', 'c']
    p.add_argument('verbs',          action='append', nargs=argparse.REMAINDER, choices=verb_choices)

    p.add_argument('--test', '-t',   action='store',             default='basic', help="Specify UVM test name [default:basic]")
    p.add_argument('--dir',  '-d',   action='store',             default=None,    help="Specify alternate directory for results.")
    p.add_argument('--verb', '-V',   action='store',             default=None,    help="Specify UVM Verbosity.")

    p.add_argument('--sim',  '-s',   action='store',             default=None,    help="Add simulation opts as a string to simulator command-line.")
    p.add_argument('--comp', '-c',   action='store',             default=None,    help="Add compilation opts as a string to compiler command-line.")

    p.add_argument('--topo',         action='store', type=int,   default=None,    help="Print UVM topology at this depth.")
    p.add_argument('--wdog', '-w',   action='store', type=int,   default=None,    help="Time (in ns) at which the testbench will watchdog timeout.")
    p.add_argument('--gui',  '-g',   action='store_true',        default=False,   help="Run DVE in GUI mode.")
    p.add_argument('--fsdb', '-f',   action='store_true',        default=False,   help="Run with Verdi wave dumping.")

    Options = p.parse_args()

    if Options.verbs == [[]]:
        Options.verbs = [['bld', 'sim']]

########################################################################################
def run_cmd(cmd_line):
    """
    Run the given command in a sub-process, exiting on failure
    """

    print "++ Running", cmd_line

    proc = subprocess.Popen(args=cmd_line, shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, stdin=file(os.devnull, 'r+'))
    while True:
        line = proc.stdout.readline()
        if not line:
            break
        print line.rstrip()

    returnCode = proc.poll()
    if returnCode != 0:
        print
        print '*'*40
        print ' '*15 + "FAILED"
        print '*'*40
        sys.exit(returnCode)

########################################################################################
def clean():
    """
    Remove unwanted directories and files.
    """
    from shutil import rmtree

    print "Cleaning..."
    for dname in GLBL['CLEAN_DIRS']:
        try:
            rmtree(dname)
            print "++ Removed dir", dname
        except:
            pass

    for fname in GLBL['CLEAN_FILES']:
        try:
            os.remove(fname)
            print "++ Removed file", fname
        except:
            pass

########################################################################################
def build():
    """
    Build the simulation executable
    """

    # determine all of the vkits and flists
    vkits = [os.path.join(GLBL['VKITS_DIR'], it, "%s.flist" % it) for it in GLBL['VKITS']]
    flists = [GLBL['UVM_FLIST']] + vkits + GLBL['FLISTS']

    if not os.path.exists(GLBL['VCOMP_DIR']):
        os.makedirs(GLBL['VCOMP_DIR'], 0777)

    build_cmd = GLBL['BUILD_TOOL']
    build_cmd += ' -o %s -Mupdate' % (os.path.join(GLBL['VCOMP_DIR'], 'sim.exe'))
    build_cmd += " %s/src/dpi/uvm_dpi.cc" % GLBL['UVM_DIR']
    build_cmd += ' -f ' + ' -f '.join(flists)
    build_cmd += " %s" % GLBL['BUILD_OPTIONS']

    if GLBL['PLI_FILES']:
        build_cmd += ' -P ' + ' '.join(GLBL['PLI_FILES'])

    # compile-time options specified on command-line
    if Options.comp:
        build_cmd += " " + Options.comp

    cmd_line = '%s %s=1 -N build "%s"' % (GLBL['LSF_SUBMIT_TOOL'], GLBL['LSF_BUILD_LICS'], build_cmd)
    run_cmd(cmd_line)

########################################################################################
def simulate(test_name):
    """
    Run the simulation
    """

    sim_cmd = os.path.join(GLBL['VCOMP_DIR'], 'sim.exe')
    sim_cmd += " +UVM_TESTNAME=%s_test_c" % test_name

    sim_dir = os.path.join('sim', (Options.dir if Options.dir else test_name))
    sim_cmd += " -l %s/logfile" % sim_dir

    if not os.path.exists(sim_dir):
        os.makedirs(sim_dir)

    # OPTIONS
    if Options.verb:
        sim_cmd += " +UVM_VERBOSITY=%s" % Options.verb

    if Options.topo:
        sim_cmd += " +UVM_TOPO_DEPTH=%d" % Options.topo

    if Options.wdog:
        sim_cmd += " +wdog=%d" % Options.wdog

    if Options.gui:
        sim_cmd += GLBL['SIM_GUI']

    elif Options.fsdb:
        # make .signal_list file
        sigList = os.path.join(sim_dir, '.signal_list')
        with open(sigList, 'w') as f:
            print >>f, "0 %s" % GLBL['TB_TOP']

        sim_cmd += " +fsdb_trace +fsdb_outfile=%s +fsdb_siglist=%s" % (os.path.join(sim_dir, "waves.fsdb", sigList))

    # add simulation command-line options
    if Options.sim:
        sim_cmd += " " + Options.sim

    cmd_line = '%s %s=1 -N %s "%s"' % (GLBL['LSF_SUBMIT_TOOL'], GLBL['LSF_SIM_LICS'], test_name, sim_cmd)
    run_cmd(cmd_line)

########################################################################################
if __name__ == '__main__':
    setup_globals()
    parse_args()

    verbs = Options.verbs[0]

    if 'cln' in verbs or 'c' in verbs:
        clean()

    if 'bld' in verbs or 'b' in verbs:
        build()

    if 'sim' in verbs or 's' in verbs:
        simulate(Options.test)

    # if we get here, we must have passed
    sys.exit(0)
